SistemaPrestamos/Models/Prestamo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaPrestamos.Models
{
    public class Prestamo
    {
        public int Id { get; set; }
        [Display(Name = "Código")]
        public string Codigo { get; set; }
        [Display(Name = "Monto"), Required(ErrorMessage = "El campo {0} es requerido")]
        public float Monto { get; set; }
        [Display(Name = "Interes mensual"), Required(ErrorMessage = "El campo {0} es requerido")]
        public float Interes { get; set; }
        public DateTime Fecha { get; set; }

        [Display(Name = "Cliente"), Required(ErrorMessage = "El campo {0} es requerido")]
        public int ClienteId { get; set; }

        [Display(Name = "Forma de pago"), Required(ErrorMessage = "El campo {0} es requerido")]
        public int FormaPagoId { get; set; }
        public string EstadoPrestamo { get; set; }
        public string EstadoComision { get; set; }
        public Cliente Cliente { get; set; }
        public FormaPago FormaPago { get; set; }
        public List<Abono> Abonos { get; set; }
        public List<Comisione> Comisiones { get; set; }
        public bool Estado { get; set; }
    }
}

SistemaPrestamos/Controllers/AbonosController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPrestamos.Context;
using SistemaPrestamos.Services.Abonos;
using SistemaPrestamos.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaPrestamos.Controllers
{
    public class AbonosController : Controller
    {

        /// <summary>
        ///     Contexto de base de datos
        /// </summary>
        private readonly PrestamosContext _context;

        /// <summary>
        ///     Interface de IMapper
        /// </summary>
        private readonly IMapper _mapper;

        /// <summary>
        ///     Servicio de operaciones y consultas para prestamos
        /// </summary>
        private readonly IServiceAbonos _ServiceAbonos;

        /// <summary>
        ///     Constructor base, inicializa dependencias
        /// </summary>
        /// <param name="context"></param>
        /// <param name="mapper"></param>
        public AbonosController(PrestamosContext context, IMapper mapper, IServiceAbonos ServiceAbonos)
        {
            _context = context;
            _mapper = mapper;
            _ServiceAbonos = ServiceAbonos;
        }

        /// <summary>
        ///     Vista inicial de los abonos
        /// </summary>
        /// <param name="IdPrestamo"></param>
        /// <returns></returns>
        public async Task<IActionResult> Index(int IdPrestamo)
        {
            var prestamo = await _context.Prestamos.FirstOrDefaultAsync(x => x.Id == IdPrestamo);
            if (prestamo is null) return NotFound();

            var modelo = new AbonosViewModels(_context, IdPrestamo);
            modelo.DetallePrestamo();

            modelo.Abonos = await _ServiceAbonos.GetAllByPrestamo(IdPrestamo);
            modelo.Saldo = (modelo.Prestamo - modelo.Abonos.Sum(x => x.Capital)).ToString("F");
            modelo.Pagado = _context.Prestamos.FirstOrDefault(x => x.Id == IdPrestamo).Monto == modelo.Abonos.Sum(s => s.Capital);

            modelo.Minimo = (float)Math.Ceiling(await _ServiceAbonos.CalculaInteres(new Models.Abono { PrestamoId = IdPrestamo, Monto = 0 }));
            modelo.Maximo = (float)Math.Ceiling((modelo.Prestamo - modelo.Abonos.Sum(x => x.Capital)) + (await _ServiceAbonos.CalculaInteres(new Models.Abono { PrestamoId = IdPrestamo, Monto = 0 })));
            modelo.Monto = (float)Math.Ceiling((decimal)modelo.Minimo);
            return View(modelo);
        }

        /// <summary>
        ///     Ejeucta abono del prestamo
        /// </summary>
        /// <param name="abonosViewModels"></param>
        /// <returns></returns>
        public async Task<IActionResult> Abonar(AbonosViewModels abonosViewModels)
        {
            await _ServiceAbonos.Abonar(new Models.Abono { Monto = abonosViewModels.Monto, PrestamoId = abonosViewModels.IdPrestamo });
            return RedirectToAction(nameof(Index), new { IdPrestamo = abonosViewModels.IdPrestamo });
        }
    }
}

SistemaPrestamos/Controllers/PrestamoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaPrestamos.Context;
using SistemaPrestamos.Models;
using SistemaPrestamos.Services.Prestamos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaPrestamos.Controllers
{
    public class PrestamoController : Controller
    {
        /// <summary>
        ///     Contexto de base de datos
        /// </summary>
        private readonly PrestamosContext _context;

        /// <summary>
        ///     Interface de IMapper
        /// </summary>
        private readonly IMapper _mapper;

        /// <summary>
        ///     Servicio de operaciones y consultas para prestamos
        /// </summary>
        private readonly IPrestamos _ServicePrestamos;
        public PrestamoController(PrestamosContext context, IMapper mapper, IPrestamos ServicePrestamos)
        {
            _context = context;
            _mapper = mapper;
            _ServicePrestamos = ServicePrestamos;
        }
        public async Task<IActionResult> Index() { 
            return View(await _ServicePrestamos.GetAll());
        }
        

        /// <summary>
        ///     Vista para crear un nuevo prestamo
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            var codigo = (_context.Prestamos.Count() + 1).ToString();
            codigo = codigo.ToString().PadLeft(5, '0');
            ViewBag.Clientes = _context.Clientes.Select(cl => new SelectListItem { Value = cl.Id.ToString(), Text = cl.Nombre }).ToList();
            ViewBag.FormaPago = _context.FormaPagos.Select(cl => new SelectListItem { Value = cl.Id.ToString(), Text = cl.Nombre }).ToList();
            return View(new Prestamo() { Codigo = codigo.ToString() });
        }

        /// <summary>
        ///     Post de creación de un nuevo prestamo
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Create(Prestamo prestamo)
        {
            var result = await _ServicePrestamos.Create(prestamo);
            if (result.Id == default) return View();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update()
        {
            return View();
        }

        public async Task<IActionResult> Update(Prestamo prestamo)
        {
            return View();
        }
    }
}

SistemaPrestamos/Views/Prestamo/Create.cshtml
@model SistemaPrestamos.Models.Prestamo

@{
    ViewData["Title"] = "Create";
}

<div class="card mt-5">
    <div class="card-header bg-dark text-light ml-0 row container">
        <div class="col-md-6">
            <i class="fa fa-save"></i>&nbsp;Crear nuevo prestamo
        </div>
        <div class="col-md-6 text-right"> </div>
    </div>
    <div class="card-body">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" readonly/>
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClienteId" class="control-label"></label>
                <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.Clientes"></select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Monto" class="control-label"></label>
                <input asp-for="Monto" class="form-control" />
                <span asp-validation-for="Monto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Interes" class="control-label"></label>
                <input asp-for="Interes" class="form-control" />
                <span asp-validation-for="Interes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FormaPagoId" class="control-label"></label>
                <select asp-for="FormaPagoId" class="form-control" asp-items="ViewBag.FormaPago"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SistemaPrestamos/Views/Prestamo/Index.cshtml
@model IEnumerable<PrestamosDTO>

@{
    ViewData["Title"] = "Index";
}

<div class="card" style="margin-top:30px">
    <div class="card-header bg-dark text-light ml-0 row container">
        <div class="col-md-6">
            <i class="fa fa-list-ul"></i>&nbsp;Prestamos
        </div>
        <div class="col-md-6 text-right">
            <a asp-action="Create" asp-controller="Prestamo" class="btn btn-primary btn-sm text-white"><i class="fa fa-plus"></i></a>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Código </th>
                    <th>Fecha Prestamo </th>
                    <th>Cliente</th>
                    <th>Monto</th>
                    <th>Interes</th>
                    <th>Interes ganado</th>
                    <th>Capital abonado</th>
                    <th>Estado prestamo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @item.Codigo
                    </td>
                    <td>
                        @item.Fecha
                    </td>
                    <td>
                        @item.Cliente
                    </td>
                    <td>
                        @item.Monto.ToString("F")
                    </td>
                    <td>
                        @item.Tasa %
                    </td>
                    <td>
                        @item.AbonadoInteres.ToString("F")
                    </td>
                    <td>
                        @item.AbonadoCapital.ToString("F")
                    </td>
                    <td>
                        @item.Estado
                    </td>
                    <td>
                        <a asp-action="Index" asp-controller="Abonos" asp-route-IdPrestamo="@item.IdPrestamo" title="Abonos"
                           class="btn btn-info btn-sm text-white"><i class="fa fa-pencil"></i></a>
                    </td>
                </tr>
                }
            </tbody>
        </table>

    </div>
</div>