SistemaPrestamos/Controllers/ClienteController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPrestamos.Context;
using SistemaPrestamos.Models;
using SistemaPrestamos.Models.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaPrestamos.Controllers
{
    public class ClienteController : Controller
    {
        private readonly PrestamosContext context;
        private readonly IMapper mapper;

        public ClienteController(PrestamosContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var clientes = await context.Clientes.Where(x => x.Estado.Equals(true)).ToListAsync();
            return View(mapper.Map<List<ClienteDTO>>(clientes));
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ClienteDTO clienteDTO)
        {
            if (ModelState.IsValid)
            {
                var cliente = mapper.Map<Cliente>(clienteDTO);
                cliente.Estado = true;
                await context.Clientes.AddAsync(cliente);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clienteDTO);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var cliente = await context.Clientes.FirstOrDefaultAsync(x => x.Id.Equals(id.GetValueOrDefault()));
            if (cliente == null) return NotFound();
            var clienteDTO = mapper.Map<ClienteDTO>(cliente);
            return View(clienteDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ClienteDTO clienteDTO)
        {
            if (ModelState.IsValid)
            {
                var cliente = mapper.Map<Cliente>(clienteDTO);
                context.Clientes.Update(cliente);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clienteDTO);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var cliente = await context.Clientes.FirstOrDefaultAsync(x => x.Id.Equals(id.GetValueOrDefault()));
            if (cliente == null) return NotFound();
            var clienteDTO = mapper.Map<ClienteDTO>(cliente);
            return View(clienteDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var cliente = await context.Clientes.FirstOrDefaultAsync(x => x.Id.Equals(id));

            if (cliente == null) return NotFound();
            cliente.Estado = false;
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

SistemaPrestamos/Controllers/ComisioneController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPrestamos.Context;
using SistemaPrestamos.Models;
using SistemaPrestamos.Models.DTOs;
using SistemaPrestamos.Utilidad;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaPrestamos.Controllers
{
    public class ComisioneController : Controller
    {
        private readonly PrestamosContext context;
        private readonly IMapper mapper;

        public ComisioneController(PrestamosContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            var cliente = context.Clientes.FirstOrDefault(x => x.Cedula.Equals("NODEFINIDO"));
            if (cliente is null) return NotFound();
            var prestamos = context.Prestamos.Where(x => x.EstadoPrestamo.Equals(Helper.ESTADOPRESTAMO.PAGADO.ToString()) && x.EstadoComision.Equals(Helper.ESTADOCOMISION.PENDIENTE.ToString())).ToList();
            return View(new ComisionDTO { Id = cliente.Id, Nombre = cliente.Nombre, Prestamos = prestamos });
        }

        public JsonResult ObtenerMontoDePrestamoPorId(int id)
        {
            return Json(context.Prestamos.Select(x => new { x.Id, x.Monto, x.EstadoComision }).FirstOrDefault(x => x.Id.Equals(id)));
        }

        public async Task<JsonResult> GuardarComision(List<ComisionDTO> comisionDTO)
        {
            var comisiones = mapper.Map<List<Comisione>>(comisionDTO);
            await context.Comisiones.AddRangeAsync(comisiones);
            foreach (var item in comisiones)
            {
                var prestamo = await context.Prestamos.FirstOrDefaultAsync(x => x.Id.Equals(item.PrestamoId));
                prestamo.EstadoComision = Helper.ESTADOCOMISION.PAGADO.ToString();
            }
            int save = await context.SaveChangesAsync();
            return Json(new { Data = save });
        }
    }
}

SistemaPrestamos/Controllers/FormaPagoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPrestamos.Context;
using SistemaPrestamos.Models;
using SistemaPrestamos.Models.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaPrestamos.Controllers
{
    public class FormaPagoController : Controller
    {
        private readonly PrestamosContext context;
        private readonly IMapper mapper;

        public FormaPagoController(PrestamosContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var formaPagos = await context.FormaPagos.Where(x => x.Estado.Equals(true)).ToListAsync();
            return View(mapper.Map<List<FormaPagoDTO>>(formaPagos));
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(FormaPagoDTO formaPagoDTO)
        {
            if (ModelState.IsValid)
            {
                var formaPago = mapper.Map<FormaPago>(formaPagoDTO);
                formaPago.Estado = true;
                await context.FormaPagos.AddAsync(formaPago);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(formaPagoDTO);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var formaPago = await context.FormaPagos.FirstOrDefaultAsync(x => x.Id.Equals(id.GetValueOrDefault()));
            if (formaPago == null) return NotFound();
            var formaPagoDTO = mapper.Map<FormaPagoDTO>(formaPago);
            return View(formaPagoDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(FormaPagoDTO formaPagoDTO)
        {
            if (ModelState.IsValid)
            {
                var formaPago = mapper.Map<FormaPago>(formaPagoDTO);
                context.FormaPagos.Update(formaPago);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(formaPagoDTO);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var formaPago = await context.FormaPagos.FirstOrDefaultAsync(x => x.Id.Equals(id.GetValueOrDefault()));
            if (formaPago == null) return NotFound();
            var formaPagoDTO = mapper.Map<FormaPagoDTO>(formaPago);
            return View(formaPagoDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var formaPago = await context.FormaPagos.FirstOrDefaultAsync(x => x.Id.Equals(id));

            if (formaPago == null) return NotFound();
            formaPago.Estado = false;
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

SistemaPrestamos/Controllers/PrestamoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaPrestamos.Context;
using SistemaPrestamos.Models;
using SistemaPrestamos.Services.Prestamos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaPrestamos.Controllers
{
    public class PrestamoController : Controller
    {
        /// <summary>
        ///     Contexto de base de datos
        /// </summary>
        private readonly PrestamosContext _context;

        /// <summary>
        ///     Interface de IMapper
        /// </summary>
        private readonly IMapper _mapper;

        /// <summary>
        ///     Servicio de operaciones y consultas para prestamos
        /// </summary>
        private readonly IPrestamos _ServicePrestamos;
        public PrestamoController(PrestamosContext context, IMapper mapper, IPrestamos ServicePrestamos)
        {
            _context = context;
            _mapper = mapper;
            _ServicePrestamos = ServicePrestamos;
        }
        public async Task<IActionResult> Index() { 
            return View(await _ServicePrestamos.GetAll());
        }
        

        /// <summary>
        ///     Vista para crear un nuevo prestamo
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            var codigo = (_context.Prestamos.Count() + 1).ToString();
            codigo = codigo.ToString().PadLeft(5, '0');
            ViewBag.Clientes = _context.Clientes.Select(cl => new SelectListItem { Value = cl.Id.ToString(), Text = cl.Nombre }).ToList();
            ViewBag.FormaPago = _context.FormaPagos.Select(cl => new SelectListItem { Value = cl.Id.ToString(), Text = cl.Nombre }).ToList();
            return View(new Prestamo() { Codigo = codigo.ToString() });
        }

        /// <summary>
        ///     Post de creación de un nuevo prestamo
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Create(Prestamo prestamo)
        {
            var result = await _ServicePrestamos.Create(prestamo);
            if (result.Id == default) return View();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update()
        {
            return View();
        }

        public async Task<IActionResult> Update(Prestamo prestamo)
        {
            return View();
        }
    }
}

SistemaPrestamos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaPrestamos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/limonte-sweetalert2/sweetalert2.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaPrestamos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prestamo" asp-action="Index">Prestamos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comisione" asp-action="Index">Comisiones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="IngresosEgresos" asp-action="Index">Ingresos y Egresos</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Mantenimientos
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Cliente" asp-action="Index">Clientes</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="FormaPago" asp-action="Index">Forma de Pagos</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SistemaPrestamos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/limonte-sweetalert2/sweetalert2.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>